ERROR:root:'int' object has no attribute 'to_dict'
